service: service

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: sa-east-1
  profile: yourAwsProfile # Use an already configured AWS profile in your terminal or comment this line and passed as $ export AWS_PROFILE=youAwsProfile
  timeout: 10
  environment:
      DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

custom:
  webpackIncludeModules: true

functions:
  initFill:
    handler: initFill.initFill
    package:
      invidually: true

  listAll:
    handler: listAll.listAll
    package:
      invidually: true

  getById:
    handler: getById.getById
    package:
      invidually: true

  addOne:
    handler: addOne.addOne
    package:
      invidually: true

  updateOne:
    handler: updateOne.updateOne
    package:
      invidually: true

  deleteOne:
    handler: deleteOne.deleteOne
    package:
      invidually: true

resources:
  Resources:
    ProductsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
